packages:
  - './standard/scripts'
  - './standard/tests'
  - './standard/bundle'
  - './standard/packages/*'
  - './premium/tests'
  - './premium/bundle'
  - './premium/packages/*'
  - './scripts'
  - './contrib/*'
  - './examples/*'
  # getting confused by monorepo setup with both React 18 and React 19 somehow,
  # importing both. Eventually upgrade all to 19
  - '!./examples/t3-app'
