packages:
  - ./standard
  - ./standard/tests
  - ./standard/bundle
  - ./standard/packages/*
  - ./premium
  - ./premium/tests
  - ./premium/bundle
  - ./premium/packages/*
  - ./scripts
  - ./contrib/*
  - ./examples/*
