name: Release
on:
  # Run manually from UI
  workflow_dispatch:
    inputs:
      skipVersionBump:
        description: Skip version bump
        type: boolean
        required: false
        default: false

env:
  TZ: "America/New_York"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }} # for sync-repos pull/push later on
          fetch-depth: 0 # fetches ALL history. needed for sync-repos operations

      # for sync-repos pull/push later on
      - name: Setup Git User
        run: |
          git config --global user.name "${{ github.triggering_actor }}" && \
          git config --global user.email "${{ github.triggering_actor }}@users.noreply.github.com"

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: 'pnpm'

          # Mutates .npmrc to allow for NPM publishing
          # Will expect the NODE_AUTH_TOKEN environment variable (see below)
          registry-url: 'https://registry.npmjs.org'

      # - name: Setup Turbo Cache
      #   uses: actions/cache@v3
      #   with:
      #     path: node_modules/.cache/turbo
      #     key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
      #     restore-keys: turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install Dependencies
        run: |
          pnpm \
            --filter '!./standard' \
            --filter '!./examples/**' \
            --filter '!@fullcalendar/angular' \
            --filter '!@fullcalendar-tests/*' \
            install

      - name: Lint
        run: |
          pnpm \
            --filter '!./standard' \
            --filter '!./examples/**' \
            --filter '!@fullcalendar/angular' \
            --filter '!@fullcalendar-tests/*' \
            run lint

      - name: Bump Versions
        if: success() && !inputs.skipVersionBump
        run: pnpm run version-bump

      - name: Build
        run: |
          pnpm \
            --filter '!./standard' \
            --filter '!./examples/**' \
            --filter '!@fullcalendar/angular' \
            --filter '!@fullcalendar-tests/*' \
            run build
          pnpm run archive

      # execute only contrib tests, as "smoke" tests. they're fast
      - name: Test
        run: |
          pnpm \
            --filter './contrib/**' \
            --filter '!@fullcalendar/angular' \
            run test

      # # NOTE: RELEASE_GITHUB_TOKEN must have permissions to push to protected branches
      # # NOTE: do git-push first. another git-push will happen after subrepos are updated,
      # # but if that one fails, we might be in a bad state w/ subrepos.
      # - name: Sync Repos
      #   run: |
      #     pnpm run meta:update
      #     pnpm run sync-repos

      # - name: Tag & Create GitHub Releases
      #   env:
      #     GH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }} # for GitHub CLI
      #   run: pnpm run tag-and-release

      # - name: Publish to NPM
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: pnpm run publish
