name: Release
on:
  # Run manually from UI
  workflow_dispatch: {}

env:
  TZ: "America/New_York"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }} # for sync-repos pull/push later on
          fetch-depth: 0 # fetches ALL history. needed for sync-repos operations

      # for sync-repos pull/push later on
      - name: Setup Git User
        run: |
          git config --global user.name "${{ github.triggering_actor }}" && \
          git config --global user.email "${{ github.triggering_actor }}@users.noreply.github.com"

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: 'pnpm'

          # Mutates .npmrc to allow for NPM publishing
          # Will expect the NODE_AUTH_TOKEN environment variable (see below)
          registry-url: 'https://registry.npmjs.org'

      # - name: Setup Turbo Cache
      #   uses: actions/cache@v3
      #   with:
      #     path: node_modules/.cache/turbo
      #     key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
      #     restore-keys: turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install Dependencies
        run: |
          pnpm \
            --filter '!./standard' \
            --filter '!./examples/**' \
            --filter '!@fullcalendar-tests/*' \
            install

      - name: Lint
        run: |
          pnpm \
            --filter '!./standard' \
            --filter '!./examples/**' \
            --filter '!@fullcalendar-tests/*' \
            run lint

      - name: Bump Versions
        run: pnpm run version-bump

      - name: Build
        run: |
          pnpm \
            --filter '!./standard' \
            --filter '!./examples/**' \
            --filter '!@fullcalendar-tests/*' \
            run build
          pnpm run archive

      # execute only contrib tests, as "smoke" tests. they're fast
      - name: Test
        run: |
          pnpm \
            --filter './contrib/**' \
            run test

      - name: Tag & Create GitHub Releases
        env:
          GH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }} # for GitHub CLI
        run: pnpm run tag-and-release

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run publish

      - name: Sync Repos
        # Don't mark the whole workflow as failed if this set fails
        continue-on-error: true

        #
        # RELEASE_GITHUB_TOKEN must have permissions to push to protected branches
        #
        run: |
          echo "Pulling latest and rebasing version-bump commit atop..."
          git pull --rebase
          echo "Pushing..."
          git push

          echo "Updating subrepo configs..."
          pnpm run meta:update
          git commit -m 'meta:update'
          echo "Pushing..."
          git push

          echo "Syncing subrepos with latest commits..."
          echo "(Will record new state of subrepos on HEAD and push...)"
          pnpm run sync-repos
